=== AlexejGomozov/JWD.school.task_03/resources/tariffsTest.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/tariffsTest"
        xmlns:tns="http://www.example.com/tariffsTest"
        elementFormDefault="qualified">

  <element name="tariffs">
    <complexType>
      <sequence>
        <element ref="tns:tariff"   minOccurs="2" maxOccurs="unbounded"/>
      </sequence>
    </complexType>
  </element>

  <element name="tariff" type="tns:tariff" abstract="true"/>
  <element name="start-tariff" type="tns:start-tariff" substitutionGroup="tns:tariff"/>

  <complexType name="tariff">
    <sequence>
      <element name="operator-name" type="tns:operator"/>
      <element name="payroll" type="double"/>
      <element name="year" type="gYearMonth"/>
      <element name="connection-fee" type="double"/>
      <element name="calls" type="tns:call-price"/>
      <element name="sms" type="tns:sms-price"/>
      <element name="tariffication" type="tns:tariffications"/>
    </sequence>

    <attribute name="id" type="tns:tariffID" use="required"/>
    <attribute name="title" type="string" use="optional"/>
  </complexType>


  <complexType name="start-tariff">
    <complexContent>
      <extension base="tns:tariff">
        <sequence>
          <element name="favorite-number" type="integer"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>


  <simpleType name="operator">
    <restriction base="string">
      <enumeration value="a1" />
      <enumeration value="mts" />
      <enumeration value="life"/>
    </restriction>
  </simpleType>

  <complexType name="call-price">
    <sequence>
      <element name="call-prices-on-net" type="double"/>
      <element name="call-prices-on-another-network" type="double"/>
      <element name="call-prices-to-landline-phones" type="double"/>
    </sequence>
  </complexType>

  <simpleType name="tariffications">
    <restriction base="string">
      <enumeration value="sec12"/>
      <enumeration value="sec60"/>
    </restriction>
  </simpleType>

  <simpleType name="sms-price">
    <restriction base="string">
      <enumeration value="sms"/>
      <enumeration value="mms"/>
    </restriction>
  </simpleType>

  <simpleType name="tariffID">
    <restriction base="ID">
      <pattern value="tariff-(\d{1,3}\.){3}\d{1,3}"/>
    </restriction>
  </simpleType>

</schema>

=== AlexejGomozov/JWD.school.task_03/resources/tariffsTest.xml
<?xml version="1.0" encoding="UTF-8" ?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/tariffsTest"
         xsi:schemaLocation="http://www.example.com/tariffsTest tariffsTest.xsd">

    <start-tariff id="tariff-1.1.345.543" title="start">
        <operator-name>a1</operator-name>
        <payroll>9.0</payroll>
        <year>2021-10</year>
        <connection-fee>2.0</connection-fee>
        <calls>
            <call-prices-on-net>0.052</call-prices-on-net>
            <call-prices-on-another-network>0.104</call-prices-on-another-network>
            <call-prices-to-landline-phones>0.101</call-prices-to-landline-phones>
        </calls>
        <sms>sms</sms>
        <tariffication>sec60</tariffication>
        <favorite-number>3</favorite-number>
    </start-tariff>

    <start-tariff id="tariff-1.2.444.222" title="start">
        <operator-name>life</operator-name>
        <payroll>8.7</payroll>
        <year>2021-10</year>
        <connection-fee>1.0</connection-fee>
        <calls>
            <call-prices-on-net>0.045</call-prices-on-net>
            <call-prices-on-another-network>0.99</call-prices-on-another-network>
            <call-prices-to-landline-phones>0.94</call-prices-to-landline-phones>
        </calls>
        <sms>sms</sms>
        <tariffication>sec60</tariffication>
        <favorite-number>3</favorite-number>
    </start-tariff>

    <start-tariff id="tariff-1.3.143.314" title="start">
        <operator-name>mts</operator-name>
        <payroll>8.9</payroll>
        <year>2021-10</year>
        <connection-fee>1.5</connection-fee>
        <calls>
            <call-prices-on-net>0.050</call-prices-on-net>
            <call-prices-on-another-network>0.101</call-prices-on-another-network>
            <call-prices-to-landline-phones>0.95</call-prices-to-landline-phones>
        </calls>
        <sms>sms</sms>
        <tariffication>sec60</tariffication>
        <favorite-number>3</favorite-number>
    </start-tariff>

</tariffs>
