=== AlexejGomozov/JWD.school.task_03/files/tariffs.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/tariffs"
        xmlns:tns="http://www.example.com/tariffs"
        elementFormDefault="qualified">

    <element name="tariffs">
        <complexType>
            <sequence>
                <element ref="tns:tariff"   minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="tariff" type="tns:tariff" abstract="true"/>
    <element name="start" type="tns:start_tariff" substitutionGroup="tns:tariff"/>
    <element name="family" type="tns:family_tariff" substitutionGroup="tns:tariff"/>
    <element name="business" type="tns:business_tariff" substitutionGroup="tns:tariff"/>
    <element name="unlimited" type="tns:unlimited_tariff" substitutionGroup="tns:tariff"/>

    <complexType name="tariff">
        <sequence>
            <element name="operator_name" type="string"/>
            <element name="payroll" type="double"/>
            <element name="year" type="gYearMonth"/>

            <element name="calls" type="tns:call_prices"/>

            <element name="sms" type="tns:sms_price"/>

            <element name="favorite_number" type="int"/>
            <element name="connectionFee" type="double"/>
        </sequence>

        <attribute name="id" type="tns:tariffID" use="required"/>
        <attribute name="title" type="string" use="optional"/>
    </complexType>


    <complexType name="start_tariff">
        <complexContent>
            <extension base="tns:tariff">
                <sequence>
                    <element name="tariffication60Sec" type="double"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <complexType name="family_tariff">
        <complexContent>
            <extension base="tns:tariff">
                <sequence>
                    <element name="family_number" type="int"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="business_tariff">
        <complexContent>
            <extension base="tns:tariff">
                <sequence>
                    <element name="tariffication12Sec" type="double"/>
                    <element name="call_price_for_international_connection" type="double"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="unlimited_tariff">
        <complexContent>
            <extension base="tns:tariff">
                <sequence>
                    <element name="unlimited_calls_to_any_network" type="double"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

<complexType name="call_prices">
    <sequence>
        <element name="call_prices_on_net" type="double"/>
        <element name="call_prices_on_another_network" type="double"/>
        <element name="call_prices_to_landline_phones" type="double"/>
    </sequence>
</complexType>
    
    <simpleType name="sms_price">
        <restriction base="string">
            <enumeration value="short_sms"/>
            <enumeration value="multimedia_mms"/>
        </restriction>
    </simpleType>

<simpleType name="tariffID">
    <restriction base="ID">
        <pattern value="tariff-(\d{1,3}\.){3}\d{1,3}"/>
    </restriction>
</simpleType>

</schema>

=== AlexejGomozov/JWD.school.task_03/files/tariffs.xml
<?xml version="1.0" encoding="utf-8" ?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.com/tariffs"
        xsi:schemaLocation="http://www.example.com/tariffs tariffs.xsd">

    <start id="tariff-123.233.345.543">
       <operator_name>A1</operator_name>
        <payroll>9.0</payroll>
        <year>2021-10</year>
        <calls>
            <call_prices_on_net>0.052</call_prices_on_net>
            <call_prices_on_another_network>0.104</call_prices_on_another_network>
            <call_prices_to_landline_phones>0.101</call_prices_to_landline_phones>
        </calls>
        <sms>short_sms</sms>
        <favorite_number>1</favorite_number>
        <connectionFee>2.0</connectionFee>
        <tariffication60Sec>0.54</tariffication60Sec>
    </start>
    
    <start id="tariff-122.333.444.222">
        <operator_name>life</operator_name>
        <payroll>8.7</payroll>
        <year>2021-10</year>
        <calls>
            <call_prices_on_net>0.045</call_prices_on_net>
            <call_prices_on_another_network>0.99</call_prices_on_another_network>
            <call_prices_to_landline_phones>0.94</call_prices_to_landline_phones>
        </calls>
        <sms>short_sms</sms>
        <favorite_number>1</favorite_number>
        <connectionFee>1.0</connectionFee>
        <tariffication60Sec>0.45</tariffication60Sec>
    </start>
    
    <start id="tariff-113.221.143.314">
        <operator_name>mts</operator_name>
        <payroll>8.9</payroll>
        <year>2021-10</year>
        <calls>
            <call_prices_on_net>0.050</call_prices_on_net>
            <call_prices_on_another_network>0.101</call_prices_on_another_network>
            <call_prices_to_landline_phones>0.95</call_prices_to_landline_phones>
        </calls>
        <sms>short_sms</sms>
        <favorite_number>2</favorite_number>
        <connectionFee>1.5</connectionFee>
        <tariffication60Sec>0.50</tariffication60Sec>
    </start>

   <family id="tariff-221.331.345.212">
       <operator_name>A1</operator_name>
       <payroll>6.5</payroll>
       <year>2021-10</year>
       <calls>
           <call_prices_on_net>0.045</call_prices_on_net>
           <call_prices_on_another_network>0.104</call_prices_on_another_network>
           <call_prices_to_landline_phones>0.103</call_prices_to_landline_phones>
       </calls>
       <sms>short_sms</sms>
       <favorite_number>1</favorite_number>
       <connectionFee>3</connectionFee>
       <family_number>5</family_number>
   </family>
    
    <family id="tariff-331.331.311.212">
        <operator_name>life</operator_name>
        <payroll>5.0</payroll>
        <year>2021-10</year>
        <calls>
            <call_prices_on_net>0.038</call_prices_on_net>
            <call_prices_on_another_network>0.99</call_prices_on_another_network>
            <call_prices_to_landline_phones>0.101</call_prices_to_landline_phones>
        </calls>
        <sms>short_sms</sms>
        <favorite_number>1</favorite_number>
        <connectionFee>3</connectionFee>
        <family_number>5</family_number>
    </family>
    
    <family id="tariff-223.331.345.541">
        <operator_name>mts</operator_name>
        <payroll>5.5</payroll>
        <year>2021-10</year>
        <calls>
            <call_prices_on_net>0.043</call_prices_on_net>
            <call_prices_on_another_network>0.103</call_prices_on_another_network>
            <call_prices_to_landline_phones>0.105</call_prices_to_landline_phones>
        </calls>
        <sms>short_sms</sms>
        <favorite_number>1</favorite_number>
        <connectionFee>3</connectionFee>
        <family_number>5</family_number>
    </family>

    <business id="tariff-223.431.315.331">
        <operator_name>A1</operator_name>
        <payroll>25.0</payroll>
        <year>2021-10</year>
        <calls>
            <call_prices_on_net>0.010</call_prices_on_net>
            <call_prices_on_another_network>0.090</call_prices_on_another_network>
            <call_prices_to_landline_phones>0.042</call_prices_to_landline_phones>
        </calls>
        <sms>multimedia_mms</sms>
        <favorite_number>5</favorite_number>
        <connectionFee>0.5</connectionFee>
        <tariffication12Sec>0.006</tariffication12Sec>
        <call_price_for_international_connection>0.090</call_price_for_international_connection>
    </business>

    <business id="tariff-223.331.341.241">
        <operator_name>life</operator_name>
        <payroll>23.0</payroll>
        <year>2021-10</year>
        <calls>
            <call_prices_on_net>0.09</call_prices_on_net>
            <call_prices_on_another_network>0.080</call_prices_on_another_network>
            <call_prices_to_landline_phones>0.030</call_prices_to_landline_phones>
        </calls>
        <sms>multimedia_mms</sms>
        <favorite_number>5</favorite_number>
        <connectionFee>0</connectionFee>
        <tariffication12Sec>0.004</tariffication12Sec>
        <call_price_for_international_connection>0.090</call_price_for_international_connection>
    </business>

    <business id="tariff-443.131.355.542">
        <operator_name>mts</operator_name>
        <payroll>25.0</payroll>
        <year>2021-10</year>
        <calls>
            <call_prices_on_net>0.010</call_prices_on_net>
            <call_prices_on_another_network>0.090</call_prices_on_another_network>
            <call_prices_to_landline_phones>0.040</call_prices_to_landline_phones>
        </calls>
        <sms>multimedia_mms</sms>
        <favorite_number>4</favorite_number>
        <connectionFee>0.5</connectionFee>
        <tariffication12Sec>0.005</tariffication12Sec>
        <call_price_for_international_connection>0.085</call_price_for_international_connection>
    </business>

    <unlimited id="tariff-243.134.455.142">
        <operator_name>A1</operator_name>
        <payroll>30.0</payroll>
        <year>2021-10</year>
        <calls>
            <call_prices_on_net>0.0</call_prices_on_net>
            <call_prices_on_another_network>0.0</call_prices_on_another_network>
            <call_prices_to_landline_phones>0.0</call_prices_to_landline_phones>
        </calls>
        <sms>multimedia_mms</sms>
        <favorite_number>3</favorite_number>
        <connectionFee>0.0</connectionFee>
        <unlimited_calls_to_any_network>12.0</unlimited_calls_to_any_network>
    </unlimited>

    <unlimited id="tariff-421.133.354.541">
        <operator_name>life</operator_name>
        <payroll>28.0</payroll>
        <year>2021-10</year>
        <calls>
            <call_prices_on_net>0.0</call_prices_on_net>
            <call_prices_on_another_network>0.0</call_prices_on_another_network>
            <call_prices_to_landline_phones>0.0</call_prices_to_landline_phones>
        </calls>
        <sms>multimedia_mms</sms>
        <favorite_number>5</favorite_number>
        <connectionFee>0.0</connectionFee>
        <unlimited_calls_to_any_network>9.0</unlimited_calls_to_any_network>
    </unlimited>

    <unlimited id="tariff-123.234.515.122">
        <operator_name>mts</operator_name>
        <payroll>31.0</payroll>
        <year>2021-10</year>
        <calls>
            <call_prices_on_net>0.0</call_prices_on_net>
            <call_prices_on_another_network>0.0</call_prices_on_another_network>
            <call_prices_to_landline_phones>0.0</call_prices_to_landline_phones>
        </calls>
        <sms>multimedia_mms</sms>
        <favorite_number>3</favorite_number>
        <connectionFee>0.0</connectionFee>
        <unlimited_calls_to_any_network>10.0</unlimited_calls_to_any_network>
    </unlimited>
</tariffs>
